pipeline {
    //use kubernetes and iheritfrom the nodejs pod template and svc acc jenkins
    agent {
        kubernetes {
            inheritFrom 'nodejs'
            defaultContainer 'nodejs'
            serviceAccount 'jenkins'
        }
    }


    stages{
        stage('Test'){
            steps {
                dir('greeting-cd-pipeline') {
                    sh "node test.js"
                }
            }
        }
        // stage download and export oc tool 
        stage('Download and Export oc tool') {
            steps {
                sh '''
                    curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | tar xz
                    export PATH=$PATH:$(pwd)
                '''
            }
        }
        stage('Deploy') {
            steps {
                sh '''
                    export PATH=$PATH:$(pwd)
                    oc version
                    oc start-build greeting-metrics \
                    --follow --wait -n igalrq-metrics
                '''
            }
        }
    }
}