def mavenContainer = 'maven'
def appDir = 'shopping-cart'

pipeline {
    agent {
        kubernetes {
            inheritFrom mavenContainer
            defaultContainer mavenContainer
            serviceAccount 'jenkins'
        }
    }
    environment {
        APP_NAMESPACE = 'igalrq-security-scans'
    }
    stages {
        stage('Test') {
            steps {
                dir(appDir) {
                    sh 'MAVEN_CONFIG= ./mvnw -B clean test'
                }
            }
        }

        stage('Download oc tool') {
            steps {
                dir(appDir) {
                    sh '''
                        curl -L \
                            https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz \
                            | tar xvz
                        chmod +x oc
                        export PATH=$PATH:$(pwd)
                        oc version
                    '''
                }
            }
        }
        stage('Image Build') {
            steps {
                dir(appDir) {
                    sh """
                        export PATH=\$PATH:\$(pwd)
                        oc version
                        oc start-build security-scans \
                            --follow --wait -n ${APP_NAMESPACE}
                    """
                }
            }
        }
        stage('Security Scan') {
            steps {
                dir(appDir) {
                    sh """
                        export PATH=\$PATH:\$(pwd)
                        oc version
                        oc process -f kubefiles/security-scan-template.yml \
                        -n ${APP_NAMESPACE} \
                        -p PROJECT_NAME=${APP_NAMESPACE} \
                        -p CVE_CODE=CVE-2020-14583 \
                        | oc replace --force -n ${APP_NAMESPACE} -f -
                    """
                    sh "! ../tools/check-job-state.sh security-scans-trivy ${APP_NAMESPACE}"
                }
            }
        }
        stage('Deploy') {
            steps {
                dir(appDir) {
                    sh """
                        export PATH=\$PATH:\$(pwd)
                        oc version
                        oc patch deployment security-scans \
                            -p '{"spec": {"template": {"metadata": {"labels": {"build": "build-${BUILD_NUMBER}"}}}}}' \
                            -n ${APP_NAMESPACE}
                    """
                }
            }
        }
    }
}