pipeline {
    //add agent with label maven and svcacc jenkins
    agent {
        label 'maven'
        serviceAccount 'jenkins'
    }

    environment { APP_NAMESPACE = 'igalrq-security-scans' }
    stages {
        stage('Test') {
            steps {
                dir('shopping-cart') {
                    sh './mvnw clean test'
                }
            }
        }
        // stage to download oc tool
        stage('Download oc tool') {
            steps {
                dir('shopping-cart') {
                    sh """
                    curl -L \
                        https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz \
                        | tar xvz
                    chmod +x oc
                    export PATH=\$PATH:\$(pwd)
                    oc version
                    """
                }
            }
        }
        stage('Image Build') {
            steps {
                dir('shopping-cart') {
                    sh """
                        export PATH=\$PATH:\$(pwd)
                        oc version
                        oc start-build security-scans \
                        --follow --wait -n ${APP_NAMESPACE}
                    """
                }
            }
        }
        stage('Deploy') {
            steps {
                dir('shopping-cart') {
                    sh """
                        oc patch deployment security-scans \
                        -p '{"spec": {"template": {"metadata": {"labels": {"build": "build-${BUILD_NUMBER}"}}}}}' \
                        -n ${APP_NAMESPACE}
                    """
                }
            }
        }
    }
}
