pipeline {
    agent {
        kubernetes {
            inheritFrom 'nodejs'
            serviceAccount 'jenkins'
            defaultContainer 'nodejs'
        }
    }
    stages {
        // i should install oc tool and export in the step
        stage('Install oc tool') {
            steps {
                sh '''
                curl -L https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz | tar xz
                export PATH=$PATH:$(pwd)
                oc version
            '''
            }
        }
        // export it also in deploy stage
        stage('Deploy') {
            steps {
                sh '''
                export PATH=$PATH:$(pwd)
                oc version
                oc whoami
                oc project igalrq-deploy-strategies
                oc start-build greeting-service --follow --wait
            '''
            }
        }
    }
}
