pipeline {
  agent {
    kubernetes {
      label 'nodejs'
      defaultContainer 'nodejs'
    }
  }

  stages {
    stage ('Install Dependencies') {
      steps {
        dir ('exchange-cli') {
          sh "npm install"
        }
      }
    }

    stage ('Build') {
      steps {
        dir ('exchange-cli') {
          sh "npm run build"
        }
      }
    }
  }
}